vich_uploader:
  db_driver: orm
  mappings:
    client_image:
      uri_prefix: /images/clients
      upload_destination: '%kernel.project_dir%/public/images/clients'

      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
